# Generated by Django 5.2.6 on 2025-10-08 09:24

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ad_diwan_poems", "0001_initial"),
        ("ad_diwan_tags", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Tags",
                through="ad_diwan_tags.Tag",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
    ]
