# Generated by Django 5.2.6 on 2025-10-08 09:24

import ad_diwan.apps.mixins
import django.db.models.deletion
import django_countries.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poet",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Poet birth date",
                        null=True,
                        verbose_name="birth date",
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True,
                        help_text="Poet death date",
                        null=True,
                        verbose_name="death date",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Poet country",
                        max_length=2,
                        null=True,
                        verbose_name="country",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Poet description",
                        max_length=256,
                        verbose_name="description",
                    ),
                ),
                (
                    "details",
                    wagtail.fields.StreamField(
                        [
                            ("alert", 12),
                            ("accordion", 20),
                            ("quote", 21),
                            ("paragraph", 22),
                            ("list", 31),
                            ("video", 32),
                            ("image", 33),
                            ("document", 34),
                            ("carousel", 40),
                            ("tabs", 61),
                            ("steps", 67),
                            ("timeline", 75),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "alert-triangle",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if alert is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("soft", "Soft"),
                                        ("outline", "Outline"),
                                        ("dash", "Dash"),
                                    ],
                                    "help_text": "Alert style",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Alert level",
                                },
                            ),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "code",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Alert message",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "check-circle2",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Action label",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Action internal link",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Action external link",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Action button color",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 5),
                                        ("label", 6),
                                        ("page", 7),
                                        ("url", 8),
                                        ("color", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (10,),
                                {"help_text": "Alert actions", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 0),
                                        ("is_vertical", 1),
                                        ("style", 2),
                                        ("level", 3),
                                        ("message", 4),
                                        ("actions", 11),
                                    ]
                                ],
                                {"help_text": "Alert"},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accordion name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            14: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                                    "help_text": "Accordion style",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Wether to show or hide item content",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            17: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Item content", "required": True},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 5),
                                        ("is_expanded", 15),
                                        ("title", 16),
                                        ("content", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Accordion items", "required": True},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 13), ("style", 14), ("items", 19)]],
                                {"help_text": "Accordion"},
                            ),
                            21: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            22: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "List title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            24: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Item image"},
                            ),
                            25: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item description",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Item internal link", "required": False},
                            ),
                            27: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Item external link", "required": False},
                            ),
                            28: (
                                "wagtail.blocks.ListBlock",
                                (10,),
                                {"help_text": "Actions", "required": False},
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 24),
                                        ("title", 16),
                                        ("description", 25),
                                        ("page", 26),
                                        ("url", 27),
                                        ("actions", 28),
                                    ]
                                ],
                                {},
                            ),
                            30: (
                                "wagtail.blocks.ListBlock",
                                (29,),
                                {"help_text": "List items", "required": True},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 23), ("items", 30)]],
                                {"help_text": "List"},
                            ),
                            32: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            33: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            34: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                            35: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if carousel is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            36: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": False},
                            ),
                            37: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Caption",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 33), ("video", 36), ("caption", 37)]],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.ListBlock",
                                (38,),
                                {"help_text": "Carousel items", "required": True},
                            ),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [[("is_vertical", 35), ("items", 39)]],
                                {"help_text": "Carousel"},
                            ),
                            41: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tab name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            42: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab buttons position is reversed",
                                    "required": False,
                                },
                            ),
                            43: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("border", "Border"),
                                        ("box", "Box"),
                                        ("lift", "Lift"),
                                    ],
                                    "help_text": "Tab style",
                                },
                            ),
                            44: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab is selected",
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 0),
                                        ("is_vertical", 1),
                                        ("style", 2),
                                        ("level", 3),
                                        ("message", 4),
                                        ("actions", 11),
                                    ]
                                ],
                                {"help_text": "Alert", "required": True},
                            ),
                            46: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide which programming language is used",
                                    "required": False,
                                },
                            ),
                            47: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide copy buttons",
                                    "required": False,
                                },
                            ),
                            48: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide window buttons",
                                    "required": False,
                                },
                            ),
                            49: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Untitled",
                                    "help_text": "File name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            50: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("auto", "Auto"),
                                        ("bash", "Bash"),
                                        ("c", "C"),
                                        ("cpp", "C++"),
                                        ("csharp", "C#"),
                                        ("css", "CSS"),
                                        ("dart", "Dart"),
                                        ("dockerfile", "Dockerfile"),
                                        ("go", "Go"),
                                        ("html", "HTML"),
                                        ("java", "Java"),
                                        ("javascript", "JavaScript"),
                                        ("json", "JSON"),
                                        ("kotlin", "Kotlin"),
                                        ("lua", "Lua"),
                                        ("markdown", "Markdown"),
                                        ("php", "PHP"),
                                        ("python", "Python"),
                                        ("ruby", "Ruby"),
                                        ("rust", "Rust"),
                                        ("scss", "SCSS"),
                                        ("shell", "Shell"),
                                        ("sql", "SQL"),
                                        ("swift", "Swift"),
                                        ("typescript", "TypeScript"),
                                        ("xml", "XML"),
                                        ("yaml", "YAML"),
                                        ("plaintext", "Plain text"),
                                    ],
                                    "help_text": "Programming language",
                                },
                            ),
                            51: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code content", "required": True},
                            ),
                            52: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("show_language", 46),
                                        ("show_copy_btn", 47),
                                        ("show_window_btns", 48),
                                        ("file_name", 49),
                                        ("language", 50),
                                        ("code", 51),
                                    ]
                                ],
                                {"help_text": "Code", "required": True},
                            ),
                            53: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image caption",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            54: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image attribution",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 33), ("caption", 53), ("attribution", 54)]],
                                {"help_text": "Image", "required": True},
                            ),
                            56: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": True},
                            ),
                            57: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich text", "required": True},
                            ),
                            58: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("alert", 45),
                                        ("code", 52),
                                        ("image", 55),
                                        ("video", 56),
                                        ("text", 57),
                                    ]
                                ],
                                {"help_text": "Tab Content", "required": True},
                            ),
                            59: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 16), ("is_selected", 44), ("content", 58)]],
                                {},
                            ),
                            60: (
                                "wagtail.blocks.ListBlock",
                                (59,),
                                {"help_text": "Tab items", "required": True},
                            ),
                            61: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 41),
                                        ("is_reversed", 42),
                                        ("style", 43),
                                        ("items", 60),
                                    ]
                                ],
                                {"help_text": "Tabs"},
                            ),
                            62: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if Steps is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            63: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            64: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Item color",
                                    "required": False,
                                },
                            ),
                            65: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 63), ("icon", 5), ("color", 64)]],
                                {},
                            ),
                            66: (
                                "wagtail.blocks.ListBlock",
                                (65,),
                                {"help_text": "Steps items", "required": True},
                            ),
                            67: (
                                "wagtail.blocks.StructBlock",
                                [[("is_vertical", 62), ("items", 66)]],
                                {"help_text": "Steps"},
                            ),
                            68: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is compact",
                                    "required": False,
                                },
                            ),
                            69: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            70: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if dates should snap to icons",
                                    "required": False,
                                },
                            ),
                            71: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Item date", "required": True},
                            ),
                            72: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item content",
                                    "max_length": 128,
                                    "required": True,
                                },
                            ),
                            73: (
                                "wagtail.blocks.StructBlock",
                                [[("date", 71), ("icon", 5), ("content", 72)]],
                                {},
                            ),
                            74: (
                                "wagtail.blocks.ListBlock",
                                (73,),
                                {"help_text": "Timeline items", "required": True},
                            ),
                            75: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("is_compact", 68),
                                        ("is_vertical", 69),
                                        ("snap_to_icon", 70),
                                        ("items", 74),
                                    ]
                                ],
                                {"help_text": "Timeline"},
                            ),
                        },
                        help_text="Poet details",
                        verbose_name="details",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Poet image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(ad_diwan.apps.mixins.ChildrenPaginatorMixin, "wagtailcore.page"),
        ),
    ]
